version: "3.8"
services:
  dockeeper:
    image: ghcr.io/onflux-tech/dockeeper:latest
    container_name: dockeeper
    restart: unless-stopped
    networks:
      - your-network
    environment:
      - CLEANUP_INTERVAL_HOURS=24
      - HEALTH_CHECKS= # container1;container2;container3
      - EVO_INSTANCE=your-instance # https://your-domain-evolution-api/message/sendText/your-instance
      - EVO_APIKEY=your-api-key # 111111111111-1111-1111-111111111111
      - EVO_NUMBER=your-number # 5511999999999
      - DOCKER_MODE=standalone # standalone or swarm
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=your-network"
      - "traefik.http.routers.dockeeper.rule=Host(`dockeeper.yourdomain.com.br`)"
      - "traefik.http.routers.dockeeper.entrypoints=websecure"
      - "traefik.http.routers.dockeeper.priority=1"
      - "traefik.http.routers.dockeeper.tls.certresolver=letsencryptresolver"
      - "traefik.http.routers.dockeeper.service=dockeeper"
      - "traefik.http.services.dockeeper.loadbalancer.server.port=8080"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

networks:
  your-network:
    external: true
