name: Build and Push

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Release
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build and Push
        run: |
          docker buildx create --use --name multiarchbuilder || docker buildx use multiarchbuilder
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/dockeeper
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t $IMAGE_NAME:${{ env.RELEASE_VERSION }} \
            -t $IMAGE_NAME:latest \
            --push .

      - name: Link
        run: echo "Imagem disponível em https://github.com/orgs/${{ github.repository_owner }}/packages/container/package/dockeeper"
